version: '3.8'

services:
  postgres:
    image: postgres
    container_name: quickfix-postgres
    environment:
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]  # Comprueba que pg_isready pueda conectarse a PostgreSQL
      interval: 10s  # Intervalo entre chequeos
      timeout: 5s   # Tiempo de espera para cada chequeo
      retries: 3    # Número de intentos antes de declarar el healthcheck como fallido
    networks:
      - backend-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quick-fix-back-api
    depends_on:
      postgres:
        condition: service_healthy  # Espera hasta que el servicio postgres esté saludable
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: admin1234
      DB_NAME: postgres
      DB_PORT: 5432
      # GIN_MODE: release
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend-network
    volumes:
      - ./pkg/utils/mendoza_locations.json:/app/pkg/utils/mendoza_locations.json

volumes:
  postgres-data:
    driver: local

networks:
  backend-network:
    driver: bridge
